site_name: "Jobstats"
site_url: https://princetonuniversity.github.io/jobstats/
repo_url: "https://github.com/PrincetonUniversity/jobstats"
repo_name: PrincetonUniversity/jobstats
nav:
  - What is Jobstats?: index.md
  - Jobstats: jobstats.md
  - Setup:
    - setup/index.md
    - Prometheus: setup/prometheus.md
    - Grafana: setup/grafana.md
    - Open OnDemand: setup/ood.md
    - smail: setup/smail.md
  - Configuration File: configuration.md
  - Installation: installation.md
  - jobstats: using_jobstats.md
  - Custom Notes: notes.md
  - External Tools: external_tools.md
  - Publications: publications.md
theme:
  name: material
  features:
    - navigation.footer
    - navigation.expand
  palette:
    # light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: blue
    # dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PrincetonUniversity/jobstats
  generator: false

copyright: "&copy;2024 Princeton University. All rights reserved."
