{
 "title": "Single Job Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "JobID", "label": "Slurm JobID" },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "cgroup_cpus{jobid=\"$JobID\", step=\"\", task=\"\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m" }
  ]
 },
 "panels": [
  { "title": "Slurm Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace((irate(cgroup_cpu_user_seconds{jobid=\"$JobID\",step=\"\",task=\"\"}[5m]) / cgroup_cpus{jobid=\"$JobID\",step=\"\",task=\"\"}), \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "User on {{shostname}}"
    },
    {
     "expr": "label_replace((irate(cgroup_cpu_system_seconds{jobid=\"$JobID\",step=\"\",task=\"\"}[5m]) / cgroup_cpus{jobid=\"$JobID\",step=\"\",task=\"\"}), \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "System on {{shostname}}"
    },
    {
     "expr": "label_replace((irate(cgroup_cpu_total_seconds{jobid=\"$JobID\",step=\"\",task=\"\"}[5m]) / cgroup_cpus{jobid=\"$JobID\",step=\"\",task=\"\"}), \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Total on {{shostname}}"
    }
   ]
  },
  {
   "title": "Job CPU Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(cgroup_memory_total_bytes{jobid=\"$JobID\",step=\"\",task=\"\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Total allocated {{shostname}}"
    },
    {
     "expr": "label_replace(cgroup_memory_rss_bytes{jobid=\"$JobID\",step=\"\",task=\"\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Rss {{shostname}}"
    },
    {
     "expr": "label_replace(cgroup_memory_cache_bytes{jobid=\"$JobID\",step=\"\",task=\"\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Cache  {{shostname}}"
    },
    {
     "expr": "label_replace(cgroup_memory_used_bytes{jobid=\"$JobID\",step=\"\",task=\"\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Used  {{shostname}}"
    },
    {
     "expr": "label_replace(irate(cgroup_memory_fail_count{jobid=\"$JobID\",step=\"\",task=\"\"}[$interval]), \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Failures {{shostname}}"
    }
   ]
  },
  {
   "title": "GPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization",
     "type": "graph",
     "description": "GPU Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_duty_cycle{jobid=\"$JobID\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    },
    {
     "title": "GPU Memory utilization",
     "type": "graph",
     "description": "GPU Memory Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_memory_used_bytes{jobid=\"$JobID\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "graph",
     "description": "GPU Temperature",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_temperature_celsius{jobid=\"$JobID\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "graph",
     "description": "GPU Power Usage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "mwatt" }
     ],
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_power_usage_milliwatts{jobid=\"$JobID\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    }
   ]
  },
  { "title": "Node Stat for $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "node" },
  {
   "title": "Node $node CPU Percentage Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "IO-Wait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Node $node Total Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node:9100\"} - node_memory_MemAvailable_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Node $node Average CPU Frequency over all CPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz{instance=\"$node:9100\"})",
     "legendFormat": "Frequency"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_max_hertz{instance=\"$node:9100\"})",
     "legendFormat": "Max Frequency"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_min_hertz{instance=\"$node:9100\"})",
     "legendFormat": "Min Frequency"
    },
    {
     "expr": "sum by (instance) (rate(node_cpu_core_throttles_total{instance=\"$node:9100\"}[1m]))",
     "legendFormat": "Throttling"
    }
   ]
  },
  {
   "title": "NFS Stats for node $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{instance=\"$node:9100\",method=\"Read\",proto=\"3\"}[$interval])",
     "legendFormat": "Read requests"
    },
    {
     "expr": "irate(node_nfs_requests_total{instance=\"$node:9100\",method=\"Write\",proto=\"3\"}[$interval])",
     "legendFormat": "Write requests"
    },
    {
     "expr": "sum(irate(node_nfs_requests_total{instance=\"$node:9100\",method=~\"PathConf|Access|FsInfo|FsStat|GetAttr|Lookup|Null|ReadDir|ReadDirPlus|ReadLink\",proto=\"3\"}[$interval]))",
     "legendFormat": "Metadata reads"
    },
    {
     "expr": "sum(irate(node_nfs_requests_total{instance=\"$node:9100\",method=~\"PCommit|Create|Link|MkDir|MkNod|Remove|Rename|RmDir|SetAttr|SymLink\",proto=\"3\"}[$interval]))",
     "legendFormat": "Metadata writes"
    }
   ]
  },
  {
   "title": "Local Disc R/W for $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_write_bytes_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Write bytes"
    }
   ]
  },
  {
   "title": "GPFS Bandwidth Stats for $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_bytes_write{host=\"$node\"}[$interval])",
     "legendFormat": "Writes to {{fs}}"
    },
    {
     "expr": "rate(gpfs_bytes_read{host=\"$node\"}[$interval])",
     "legendFormat": "Reads from {{fs}}"
    }
   ]
  },
  {
   "title": "Local Disc IOPS for $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Writes"
    }
   ]
  },
  {
   "title": "GPFS Operations per sec Stats for $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_requests_write{host=\"$node\"}[$interval])",
     "legendFormat": "Write ops to {{fs}}"
    },
    {
     "expr": "rate(gpfs_requests_read{host=\"$node\"}[$interval])",
     "legendFormat": "Read ops from {{fs}}"
    }
   ]
  },
  {
   "title": "Infiniband Throughput on $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total{instance=\"$node:9100\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total{instance=\"$node:9100\"}[$interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Inifinband packet rate on $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_multicast_packets_received_total{instance=\"$node:9100\"}[$interval]))",
     "legendFormat": "Multicast packets received"
    },
    {
     "expr": "sum(rate(node_infiniband_multicast_packets_transmitted_total{instance=\"$node:9100\"}[$interval]))",
     "legendFormat": "Multicast packets sent"
    },
    {
     "expr": "sum(rate(node_infiniband_unicast_packets_received_total{instance=\"$node:9100\"}[$interval]))",
     "legendFormat": "Unicast packets received"
    },
    {
     "expr": "sum(rate(node_infiniband_unicast_packets_transmitted_total{instance=\"$node:9100\"}[$interval]))",
     "legendFormat": "Unicast packets sent"
    }
   ]
  },
  {
   "title": "Inifniband Errors on $node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_link_downed_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Downed link"
    },
    {
     "expr": "rate(node_infiniband_link_error_recovery_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Error Recoveries"
    },
    {
     "expr": "rate(node_infiniband_port_constraint_errors_received_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Discarded incoming packets on switch"
    },
    {
     "expr": "rate(node_infiniband_port_constraint_errors_transmitted_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Discarded outgoing packets on switch"
    },
    {
     "expr": "rate(node_infiniband_port_discards_transmitted_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Outgoing packets discarded due to port congestion "
    },
    {
     "expr": "rate(node_infiniband_port_errors_received_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Packets received with an error"
    },
    {
     "expr": "rate(node_infiniband_port_receive_switch_relay_errors_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Packets not forwarded by the switch"
    },
    {
     "expr": "rate(node_infiniband_port_transmit_wait_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Congestion indicator"
    },
    {
     "expr": "rate(node_infiniband_symbol_error_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "Minor link errors"
    }
   ]
  }
 ]
}